### PR TITLE
Versioning documentation

### LINKED ISSUE #1221: Clarify supported versions at Dev Center
Clarify the support for the different releases at Dev Center

### PR DESCRIPTION
**Pull request by rochoa**
This should close #1221.

### CODE REVIEW

**Comment by VictorVelarde** [comment]
IMO it's also interesting to link to https://www.npmjs.com/package/@carto/carto-vl

**Comment by rochoa** [comment]
> IMO it's also interesting to link to https://www.npmjs.com/package/@carto/carto-vl

Just added that information. 👍

**Comment by rochoa** [comment]
> LGTM, just a small comment, should we include a note about where to check for new releases at the github page or something like that?

@jsanz, that's a really good point. Apart from pointing to the Github releases page, what do you think if we listed the last three available/supported versions within this very same documentation page?

**Comment by rochoa** [comment]
> > LGTM, just a small comment, should we include a note about where to check for new releases at the github page or something like that?
> 
> @jsanz, that's a really good point. Apart from pointing to the Github releases page, what do you think if we listed the last three available/supported versions within this very same documentation page?

After checking it, that's not an easy thing to accomplish on the developers' website. However, we plan to make the changelog available, see https://github.com/CartoDB/carto-vl/issues/1186, we should link to that once it's available.

**Comment by jsanz** [comment]
> After checking it, that's not an easy thing to accomplish on the developers' website. However, we plan to make the changelog available, see #1186, we should link to that once it's available.

Nice, thanks for the update :heart:

**Pull request merged**
