### PR TITLE
Update browser support documentation

### PR DESCRIPTION
**Pull request by csubira**
https://github.com/CartoDB/support/issues/2296

### CODE REVIEW

**Comment by pablomoniz** [comment]
I'm ok too. Thank you!!

**Comment by oriolbx** [comment]
@csubira I'm not seeing this change on the Dev Center 😨 

[https://carto.com/developers/carto-vl/support/browser-support/](https://carto.com/developers/carto-vl/support/browser-support/)

Screenshot 2019-12-24 at 15 13 28

**Comment by csubira** [comment]
It's not in production yet, it would be when the new patch version of CARTO VL has been released. _(Planned before the end of this week)_

**Comment by csubira** [comment]
@oriolbx in production! Check it out!

**Comment by oriolbx** [comment]
Thanks @csubira !!

**Comment by Eh2406** [comment]
So before this change when our (a Carto customer) map shows the **wrong** data, on a device that passes `isBrowserSupported`, I can report it as a Carto vl Bug. Admittedly a hard to track down difficult to fix bug, but a bug nonetheless.  After this change if the map does not work, it may not be a Bug it may be a silently unsupported device. Under what conditions is it still a bug for the map to be completely wrong?

**Pull request merged**
