### PR TITLE
Add weighted histogram example using a table

### PR DESCRIPTION
**Pull request by VictorVelarde**
### Related to #976 
---

I adapted @rochoa 's original gist into a 'visual table' example

image

### CODE REVIEW

**Comment by VictorVelarde** [comment]
@makella we can also merge this into your advanced-examples branch in case you wanna test this at DevCenter

**Comment by makella** [comment]
ok! sounds good... do you want to merge it in there?

**Comment by makella** [comment]
p.s. -- nice one!

**Comment by VictorVelarde** [comment]
OK, I'm gonna merge it there!

**Pull request merged**
