### PR TITLE
Test min bundle

### PR DESCRIPTION
**Pull request by Jesus89**
Related to https://github.com/CartoDB/carto-vl/issues/805

- Use minified bundle for testing in CI
- Disable bundle warnings for testing
- Clean unneeded packages
- Update bundle size limit to 260KB

### CODE REVIEW

**Comment by davidmanzanares** [comment]
But, does it make sense to change all the tests every time to the minified build? I'm worried this could be counterproductive for debugging purposes.

cc: @rochoa

**Comment by Jesus89** [comment]
If you want to cover the minified bundle without adding extra tests this is the only way. However, I could add a flag to use only minified testing in CI, enabling the uncompressed bundle for testing in development.

**Comment by rochoa** [comment]
For local, I would try to avoid minified versions, but I see the value of testing the minified version in CI.

**Comment by rochoa** [comment]
> If you want to cover the minified bundle without adding extra tests this is the only way. However, I could add a flag to use only minified testing in CI, enabling the uncompressed bundle for testing in development.

That would be the best approach, I guess.

**Pull request merged**
