### PR TITLE
Improved viewport aggregations

### PR DESCRIPTION
**Pull request by davidmanzanares**
Related to https://github.com/CartoDB/carto-vl/issues/19

- [x] Work with generic expressions
- [x] Work with polygons
- [x] Work with lines

To be improved later:
- [ ] Performance
- [ ] Precision. Polygon and line intersection detection uses AABB (axis-aligned bounding boxes) as a simplification of the geometry.

Example of viewport-line (animated to see performance): 
`#eyJhIjoic2Zfc3RjbGluZXMiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcigkbGZfZmFkZC92aWV3cG9ydE1heCgkbGZfZmFkZCksMCxub3coKSUxKSwgcHJpc20pIFxud2lkdGg6IDQqJGxmX2ZhZGQvdmlld3BvcnRNYXgoJGxmX2ZhZGQpKzEiLCJmIjp7ImxuZyI6LTEyMi40NDc3ODAyMzM5NzQ2NCwibGF0IjozNy43ODE2Mzk5MjY4MzkwNn0sImciOjExLjkwNTEwODg1MjMzNTkzNCwiaCI6IkRhcmtNYXR0ZXIifQ==`

### CODE REVIEW

**Comment by Jesus89** [comment]
I have also tested that global aggregations don't allow expressions as inputs (viewport aggregations do)

**Comment by davidmanzanares** [comment]
Unit tests were already there, but I didn't complete the refactor of extracting global agg things into its own files. It should be ok now.

Yes, global aggregations are done on the server in the case of Maps API, the current API is not flexible enough for that.

**Comment by Jesus89** [comment]
OK with the tests split.

So only viewportAggs admit expressions as inputs (cluster and global Agg only properties)?

**Comment by davidmanzanares** [comment]
"cluster and global Agg only properties" for now, yes

Approved, then?

**Comment by Jesus89** [comment]
> "cluster and global Agg only properties" for now, yes

 Good to know

> Approved, then?

Yes!, but create a new ticket with the missing parts `To be improved later`, please ;)

**Comment by davidmanzanares** [comment]
:+1:

`To be improved later` tickets: https://github.com/CartoDB/carto-vl/issues/377 https://github.com/CartoDB/carto-vl/issues/378

**Pull request merged**
