### PR TITLE
Add filter example

### PR DESCRIPTION
**Pull request by elenatorro**
Related with https://github.com/CartoDB/carto-vl/issues/1172

In this first approach, we're adding a widget that allows filter data by category using the `filter` expression and the JavaScript API.

### CODE REVIEW

**Comment by makella** [comment]
@elenatorro this is good!

I have a couple of comments/questions:

- can we remove the comments that were specific to this map as a legend example and add in a few comments for the pieces related to the filter and selection buttons?

- on line 85 we call out the others labels (I need to ask you about this in the original legend example as well) since there are no other categories showing, can we remove this?
```
        layer.on('updated', () => {
            if (!initialized) {
                const legend = layer.viz.color.getLegendData({
                    othersLabel: 'Other Weather'
                });
```

**Comment by elenatorro** [comment]
> can we remove the comments...

Totally, actually the main idea is to take a final look to the code once we finish the example, clean it and keep the consistency with other examples 👌 

> others labels

Yes, we can remove this setting for sure, good catch!

**Comment by makella** [comment]
@elenatorro thanks so much for all the comment clarifications! 

As discussed, our final to do here:
- [ ] change bars back to points (as to avoid confusion with a category-like widget since information is static)

**Comment by makella** [comment]
@elenatorro ok, awesome! did a review and added some description in the legend box. LGTM. thanks for your work on this!

**Pull request merged**
