### PR TITLE
WIP: 1254 animation example enhancements

### PR DESCRIPTION
**Pull request by makella**

### CODE REVIEW

**Comment by makella** [comment]
This PR 
- adds an animation section to the examples
- moves two existing animation examples to this section
- adds 5 new examples for
  - animating over a date range
  - animating the width of features
  - adding visibility to background features
  - holding animated features
  - animating a filtered subset of data

**Comment by VictorVelarde** [comment]
I'll have a look at this tomorrow @makella 

It would be great if we could have it deployed at this at staging. I have just pushed the branch to the cdn, so you can now deploy the doc from dev-center side, if you're fine with it.

**Comment by elenatorro** [comment]
I did some minor changes regarding code styling and I I uploaded to staging here http://test-release-1-2.developers.carto-staging.com/developers/carto-vl/examples/

**Comment by makella** [comment]
thank you!!

**Pull request merged**
