### PR TITLE
Example section map structure

### PR DESCRIPTION
**Pull request by makella**
@elenatorro 

Tomorrow, when we meet, let's review:

map-set-up.html (new)
add-layer.html (reworked)
style-layer.html (reworked)

Those are the three I started with after our conversation... I'd like to explain the logic, get your feedback, and brainstorm any other ideas.

I also went ahead and changed the fonts to Roboto so I could see what that would look like :)

### CODE REVIEW

**Comment by makella** [comment]
@VictorVelarde you can use the following template as the structure for your examples... @elenatorro and I simplified and as we build concepts, we will add them in with comments as seen in this example.

Since you are working on the basics section, this should get you started:

https://github.com/CartoDB/carto-vl/blob/examples-restructure/examples/basics/style-layer.html

**Comment by VictorVelarde** [comment]
@elenatorro @makella Do these changes in the examples affect to the examples we use to illustrate the guides? 

I'm talking about those we use for showing embedded views at each step, such as eg: `./examples/maps/guides/getting-started/basic-styling.html`

**Comment by elenatorro** [comment]
Yes, we should use this convention in every example we include in the guides.

**Comment by VictorVelarde** [comment]
ok, please ping me when you have committed those changes in *./examples/guides/getting-started/*

**Comment by makella** [comment]
@VictorVelarde, as we discussed today, the pieces that are relevant for the guides is only the header titles for each step in the html.

for that purpose, `style-layer.html` is probably the best one to get started

**Comment by VictorVelarde** [comment]
@elenatorro after talking with @makella I've gone again through the new guide on "Sources", reviewing its contents and adjusting its supporting examples (now I'm using `step-1.html`, `step-2.html`... and alike and more homogeneous JS comments, following suggested example).

I think we're in a good position to merge soon these contents:
- general improvements on examples (this PR) 
- getting-started guide (PR #982)
- sources guide (PR #985)

**Comment by VictorVelarde** [comment]
Hi @makella 
@elenatorro and myself have already merged `Getting-Started` and `Sources` guides to master, following the conventions we discussed here. Some of them have been added explicitly to our 'epic-issue' guiding the whole process https://github.com/CartoDB/carto-vl/issues/950

Regarding to this PR, I see two options: 
- to merge it as it is to `master` or 
- to expand it to include the complete list of examples, dealing with https://github.com/CartoDB/carto-vl/issues/978

**Comment by makella** [comment]
@VictorVelarde as discussed, I will keep working on the examples from this branch now that we merged the latest commits from master into it.

cc @elenatorro 

thanks!

**Comment by VictorVelarde** [comment]
I think we could close now this PR, as it was replaced with the work in another PR

**Comment by makella** [comment]
👍

**Pull request closed without merging**
