### PR TITLE
Compute metadata based on viz to reduce properties

### PR DESCRIPTION
**Pull request by rochoa**
The DataFrame is computed on demand, without having to precompute features
from the original data. This removes the clone of the data. It also allows using the
cartodb_id from original data.

### CODE REVIEW

**Comment by rochoa** [comment]
I cannot run `test:user` in my local macOS environment.

**Comment by Jesus89** [comment]
What's your output when running `yarn test:user`?

Btw, you can see in CircleCI the actual error: https://circleci.com/gh/CartoDB/carto-vl/3412?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

```
Expected -0 to equal 0
```

**Comment by Jesus89** [comment]
Just fixed the tests using positive feature.ids but, what is the reason for using negative cartodb_ids?

**Comment by rochoa** [comment]
The reason is to avoid collisions in case the original GeoJSON had cartodb_ids for some features but not for all of them.

**Comment by rochoa** [comment]
BTW, this is a WIP PR, as this is totally broken right now. The requestData method doesn't consider metadata changes after first load.

**Comment by rochoa** [comment]
Anyway, as #316 is already merged into master, I'm gonna close this PR and create a new one.

**Comment by Jesus89** [comment]
For future PRs, you can change the base branch of the PR instead of closing it and create a new one.

**Comment by rochoa** [comment]
Another TIL. Thanks!

**Pull request closed without merging**
