### PR TITLE
Use vendor file from https://github.com/CartoDB/mapbox-gl-js/commit/4…

### PR DESCRIPTION
**Pull request by davidmanzanares**
Use vendor file from https://github.com/CartoDB/mapbox-gl-js/commit/4b58dc3ced816bb36199fc284ebe6f93e5f9e29c

Update MGL vendor file to get a fix for the same as https://github.com/CartoDB/carto-vl/pull/311

The problem was visible on the country borders of the basemap, particularly/usually in Africa, where many country borders disappeared.

The issue was that we were modifying one of the VAOs of MGL, and we weren't invalidating that. The patched version binds the default VAO to avoid modifying MGL VAOs

### CODE REVIEW

**Comment by davidmanzanares** [comment]
Is this ready to merge? @IagoLast

**Comment by Jesus89** [comment]
- I would use our fork as a `npm` dependency
- Are we covering the same use cases than before?
- Why are you using `click()` and `map.fire({ type`. Could we use the same function for all the user tests?

**Comment by IagoLast** [comment]
@Jesus89 

> I would use our fork as a npm dependency

+1 (different issue)

> Are we covering the same use cases than before?

Nope, less cases IMO we should try to keep all cases even when we need to use mapboxgl private methods.

> Why are you using click() and map.fire({ type. Could we use the same function for all the user tests?

As pointed [here](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.45.0-beta.1) the `map.fire` functionality was moved to be private (but still there with a slightly different API) Some events can be simulated but other ones are very hard to.  Since api changes are very easy to update I think we should rewrite the old tests (keeping them all) using the new API and forget about this.

**Comment by davidmanzanares** [comment]
Hey, I don't like the idea of using `map.fire`. That's a private method of MGL. We shouldn't depend on that, MGL patch versions and major changes with breaking changes notes can break our tests with no reason.

(https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.45.0-beta.1)

**Comment by IagoLast** [comment]
> Hey, I don't like the idea of using map.fire. That's a private method of MGL. 

Agreed BUT:

- The right fix this will take lot of effort and time while the hotfix is just a few minutes.
- We only need to check this when we change the `mapbox-gl` version, this happened 1 time in 2 months and I think we could find worst problems than that when this change happens.
- Even if the change breaks this, Is only test code so our product won't break.

So right, is not the perfect solution but I don't think is a good idea to waste time working on a shinny fix for a few tests while we have thousands of hacks in the real code.

**Comment by davidmanzanares** [comment]
> I think we could find worst problems than that when this change happens.

It shouldn't, if it happens it is a bug.

**Comment by IagoLast** [comment]
> It shouldn't, if it happens it is a bug.

I mean, since we are using `mapbox-gl` through a custom fork it could happen they change some internal and break our project right?

**Comment by IagoLast** [comment]
oh, nice @Jesus89 ;)

**Comment by Jesus89** [comment]
We close this PR since we have solved this issue in #332 and #339

**Comment by IagoLast** [comment]
should we delete the branch?

**Pull request closed without merging**
