### PR TITLE
Improve exquisite/puppeteer tests

### LINKED ISSUE #337: Non deterministic render test failures
We've seen a few times now some MGL-integration tests fail randomly on `master` since this is very difficult to reproduce, we should improve the testing framework to show more information. Not just a pixel mismatch.

For example:

- Console errors, console warns
- Uncaught exceptions
- Time, did it timeout?

### LINKED ISSUE #585: Improve render test times
Rendering test times have been increasing since we have added many render tests.

If I remember correctly, the current test framework creates a new browser per test, we could improve testing time by re-using the browser used.

### PR DESCRIPTION
**Pull request by rochoa**
## Re-use browser instance in integration/render tests
This includes https://github.com/CartoDB/carto-vl/pull/687.

## Intercepts errors happening in exquisite/puppeteer to fail tests
This should help with "Non deterministic render test failures".

A couple of examples.

1. Network failures:

While executing the test, you will get a verbose console message like:
```
Error: Request failed: URL="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.css"; Reason="net::ERR_INTERNET_DISCONNECTED"
    at Page.requestfailed (/Users/rochoa/projects/carto-vl/test/common/util.js:74:29)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page._networkManager.on.event (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Page.js:96:80)
    at emitOne (events.js:116:13)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._onLoadingFailed (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/NetworkManager.js:301:10)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
Failed to load resource: net::ERR_INTERNET_DISCONNECTED
Error: Request failed: URL="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.js"; Reason="net::ERR_INTERNET_DISCONNECTED"
    at Page.requestfailed (/Users/rochoa/projects/carto-vl/test/common/util.js:74:29)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page._networkManager.on.event (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Page.js:96:80)
    at emitOne (events.js:116:13)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._onLoadingFailed (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/NetworkManager.js:301:10)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
Failed to load resource: net::ERR_INTERNET_DISCONNECTED
    11) /geometries/collection-point/color
```

In the summary for all the tests you get a shorter message:
```
  11) Render tests:
       /geometries/collection-point/color:
     Error: Request failed: URL="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.css"; Reason="net::ERR_INTERNET_DISCONNECTED", Request failed: URL="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.js"; Reason="net::ERR_INTERNET_DISCONNECTED"
      at Object.testSST (test/common/util.js:84:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

2. Something related to CARTO VL itself

Verbose trace while executing:
```
Error: Error: Another atomic change was done before this one committed
    at Layer.update (http://localhost:5000/dist/carto-vl.js:7281:19)
    at Page._handleException (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Page.js:103:60)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (/Users/rochoa/projects/carto-vl/node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/Users/rochoa/projects/carto-vl/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
    19) /regression/layer-update
```

Message for the summary:
```
  19) Render tests:
       /regression/layer-update:
     Error: Error: Another atomic change was done before this one committed
    at Layer.update (http://localhost:5000/dist/carto-vl.js:7281:19)
      at Object.testSST (test/common/util.js:84:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Fixes #337 and fixes #585.

### CODE REVIEW

**Comment by IagoLast** [comment]
@rochoa the atomic change error is due our famous synchronicity issues but doesn't affect the test result. (it should not, maybe we just discovered the source of non-determinism)

Not the suite fails because you [throw an error](https://github.com/CartoDB/carto-vl/pull/684/files#diff-d019928c613ed79b446e1cd403c36f64R84) maybe a console.error would be better... not sure

**Comment by rochoa** [comment]
I always prefer duplication over a wrong abstraction.

**Comment by IagoLast** [comment]
> I want the suite to fail if a non-expected error happened, that's why I used the throw.

Now the tests will fail more because the atomic change error

**Comment by davidmanzanares** [comment]
> Now the tests will fail more because the atomic change error

I would look into that, that smells... a lot

**Comment by IagoLast** [comment]
> I would look into that, that smells... a lot

sure!

**Pull request merged**
