### PR TITLE
Advanced Animation guide

### PR DESCRIPTION
**Pull request by davidmanzanares**
cc: @jgoizueta @arianaescobar @makella

### CODE REVIEW

**Comment by Jesus89** [comment]
How is this one? We must merge this PR in order to create the beta release.

**Comment by davidmanzanares** [comment]
I have no idea :confused:

**Comment by makella** [comment]
@jgoizueta y @davidmanzanares 

@arianaescobar and i will review today!

**Comment by Jesus89** [comment]
Great Thanks!

**Comment by Jesus89** [comment]
We can use this one https://cartodb.github.io/carto-vl/examples/styling/animation.html for now instead of creating a new example because of the following reasons: it is done and it is fast.

**Comment by makella** [comment]
Ok, I started reading through this guide and I have a few general thoughts.

First, I feel like the guide is a little too complex and needs to break down some things further and as a first pass, simply be an introduction to animation.

Let's keep this branch to pull from for a later, more advanced guide.

If you guys are ok with that, I propose that we write a simple guide on how to create the animation that we have in the examples section (https://cartodb.github.io/carto-vl/examples/styling/animation.html).

If we can explain the parameters using that map as an example, it will be a quicker way to illustrate the general concept and as mentioned before, once that is out, we can reuse content here for a more advanced guide.

thanks!

**Comment by davidmanzanares** [comment]
Blocked until we decide what to do with this

**Comment by elenatorro** [comment]
Closing in favor of https://github.com/CartoDB/carto-vl/issues/974

**Pull request closed without merging**
