### PR TITLE
 Add performance testing infrastructure

### PR DESCRIPTION
**Pull request by IagoLast**
This uses karma and benchmark.js to get performance stats, a custom karma-reported was created to display better insights.

Summary
---

A new test/benchmark folder is created, all files ending in .perf.js are considered performance test suites where 2
global functions are availiable:

- suite
- benchmark

Group test suites using the suite function and meassure a function using `benchmark`

To run the tests just execute `yarn test:perf`

### CODE REVIEW

**Comment by IagoLast** [comment]
@davidmanzanares this is an initial approach, please let me know your opinion

@Jesus89 @davidmanzanares @rochoa @elenatorro

**Comment by davidmanzanares** [comment]
The results seems pretty inconsistent to me, do you know why?


```
First run:
getFeaturesAtPosition

ops/sec: 3765504.6675557243
Margin of error: 1.60698773540625e-8
Mean: 2.655686523552029e-7
Deviation: 6.024948940799965e-8
Variance: 3.630000973924662e-15


getFeaturesAtPosition

ops/sec: 4081088.79341549
Margin of error: 1.752703468567938e-8
Mean: 2.4503264952564127e-7
Deviation: 6.571269135302546e-8
Variance: 4.318157804857987e-15

Completed
Done in 14.95s.
```
Second run:
```
getFeaturesAtPosition

ops/sec: 5058428.150920493
Margin of error: 5.058381935400786e-9
Mean: 1.9768986929626112e-7
Deviation: 1.9990845912820087e-8
Variance: 3.996339203101156e-16


getFeaturesAtPosition

ops/sec: 4973048.4976314735
Margin of error: 1.6852423833502586e-9
Mean: 2.0108390265573976e-7
Deviation: 6.824590171240657e-9
Variance: 4.657503100539458e-17

Completed
Done in 13.44s.
```
Third run:
```
getFeaturesAtPosition

ops/sec: 4620946.491999135
Margin of error: 3.5777085226147668e-9
Mean: 2.164058817238923e-7
Deviation: 1.4602891929039865e-8
Variance: 2.1324445269121762e-16


getFeaturesAtPosition

ops/sec: 4413922.562141496
Margin of error: 2.006958725118889e-9
Mean: 2.2655585500685166e-7
Deviation: 8.25541761842099e-9
Variance: 6.815192005453571e-17

Completed
Done in 13.38s.

```

**Comment by IagoLast** [comment]
@davidmanzanares agreed 

We are using [benchmarkjs/](https://benchmarkjs.com) to capture the results and is supposed to be the reference js benchmark library...

worst execution: 3 765 504
best execution: 5 058 428


Maybe we can tweak the parameters to increase the sample size or something similar and get a more precise result, but I think this implies creating our own karma-adapter

cc @rochoa

**Comment by davidmanzanares** [comment]
Hey @IagoLast what is the current status of this? Are there any pending issues or is it ready for CR?

I think we have missed this on the project kanban, but, since we have many recurring performance problems, I think we should push this.

**Comment by IagoLast** [comment]
Hi, sorry for the delay.

I started this issue trying to use https://benchmarkjs.com/ to benchmark our code but as you comment [here](https://github.com/CartoDB/carto-vl/pull/597#issuecomment-399146007) the results were not very good.

So as a leapfrog I made a full benchmarking library based on [karma runner](https://karma-runner.github.io/2.0/index.html) to run tests in the browser.

This library has 3 parts:

 - [The core](https://github.com/iagolast/falcon-benchmark): Exposes a single benchmark function that receives a function and will return execution stats.
- [A Karma Adapter](https://github.com/IagoLast/karma-falcon-benchmark) That allows to run the core on karma.
- [A Karma Reporter](https://github.com/IagoLast/karma-falcon-benchmark-reporter) That prints the results.  


I configured this in the project and I ran some tests, the results are shown [here](https://github.com/CartoDB/carto-vl/pull/597#issuecomment-399907394)

**Comment by davidmanzanares** [comment]
Thanks for the summary! I'm gonna review all of this

**Comment by davidmanzanares** [comment]
(Wait for other CRs though)

**Pull request merged**
