### PR TITLE
Reduce number of examples [WIP]

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue https://github.com/CartoDB/carto-vl/issues/1036

* Staging branch: http://reduced-examples.developers.carto-staging.com/developers/carto-vl/examples/

* Current status:
✅  basics/add-layer.html
✅  basics/basic-style.html
✅  basics/browser-support.html
✅  advanced/hurricane-harvey.html
✅  advanced/us-population-by-county.html
✅  advanced/taxi-pickups.html
✅  advanced/ocean-bathymetry.html
✅  advanced/classification-variables.html
✅  basemap/pitch-bearing.html
✅  basemap/basemap-labels-on-top.html
✅  basemap/basemap-labels-under.html
✅  basemap/color-map-background.html
✅  basemap/project-layer.html
✅  index.html
✅  legends/choropleth-legend.html
✅  legends/category-line-legend.html
✅  legends/image-legend.html
✅  legends/unclassed-point-legend.html
✅  legends/category-point-legend.html
✅  legends/feature-and-legend-opacity.html
✅  labeling/point-labels-size-zoom.html
✅  labeling/polygon-labels.html
✅  labeling/point-labels.html
✅  labeling/point-labels-conditional-style.html
✅  labeling/cluster-labels-average.html
✅  labeling/cluster-labels-count.html
✅  animation/animate-by-date-range.html
✅  animation/animate-and-hold.html
✅  animation/animate-filtered-features.html
✅  animation/animate-color-by-date.html
✅  animation/add-feature-visibility.html
✅  animation/animate-width.html
✅  animation/animation-controls.html
✅  interactivity/hover.html
✅  interactivity/pop-up-on-hover.html
✅  interactivity/interactive-based-styling.html
✅  interactivity/interactive-filter.html
✅  interactivity/pop-up-on-click.html
✅  interactivity/click.html
✅  interactivity/interact-multiple-layers.html
✅  guides/add-legends/step-3.html
✅  guides/add-legends/step-2.html
✅  guides/add-legends/step-5.html
✅  guides/add-legends/step-9.html
✅  guides/add-legends/step-8.html
✅  guides/add-legends/step-4.html
✅  guides/add-legends/step-7.html
✅  guides/add-legends/step-6.html
✅  guides/add-legends/step-1.html
✅  guides/style-with-expressions/step-3.html
✅  guides/style-with-expressions/step-2.html
✅  guides/style-with-expressions/step-1.html
✅  guides/animated-viz/step-3.html
✅  guides/animated-viz/step-2.html
✅  guides/animated-viz/step-5.html
✅  guides/animated-viz/step-4.html
✅  guides/animated-viz/step-7.html
✅  guides/animated-viz/step-6.html
✅  guides/animated-viz/step-1.html
✅  guides/animated-viz/step-0.html
✅  guides/aggregation-and-data-summaries/step-3.html
✅  guides/aggregation-and-data-summaries/step-2.html
✅  guides/aggregation-and-data-summaries/step-1.html
✅  guides/zoom-based-styles/step-3.html
✅  guides/zoom-based-styles/step-2.html
✅  guides/zoom-based-styles/step-5.html
✅  guides/zoom-based-styles/step-8.html
✅  guides/zoom-based-styles/step-4.html
✅  guides/zoom-based-styles/step-7.html
✅  guides/zoom-based-styles/step-6.html
✅  guides/zoom-based-styles/step-1.html
✅  guides/data-driven-viz-1/step-3.html
✅  guides/data-driven-viz-1/step-2.html
✅  guides/data-driven-viz-1/step-5.html
✅  guides/data-driven-viz-1/step-9.html
✅  guides/data-driven-viz-1/step-8.html
✅  guides/data-driven-viz-1/step-4.html
✅  guides/data-driven-viz-1/step-7.html
✅  guides/data-driven-viz-1/step-6.html
✅  guides/data-driven-viz-1/step-1.html
✅  guides/getting-started/step-2.html
✅  guides/getting-started/step-1.html
✅  guides/add-interactivity/step-3.html
✅  guides/add-interactivity/step-2.html
✅  guides/add-interactivity/step-1.html
✅  guides/add-data-sources/step-3.html
✅  guides/add-data-sources/step-2.html
✅  guides/add-data-sources/step-1.html
✅  guides/add-widgets/step-3.html
✅  guides/add-widgets/step-2.html
✅  guides/add-widgets/step-1.html
✅  guides/build-custom-charts/step-3.html
✅  guides/build-custom-charts/step-2.html
✅  guides/build-custom-charts/step-5.html
✅  guides/build-custom-charts/step-4.html
✅  guides/build-custom-charts/step-6.html
✅  guides/build-custom-charts/step-1.html
✅  guides/data-driven-viz-2/step-3.html
✅  guides/data-driven-viz-2/step-2.html
✅  guides/data-driven-viz-2/step-4.html
✅  guides/data-driven-viz-2/step-1.html
✅  styling/style-with-variables.html
✅  styling/color-schemes.html
✅  styling/image-external.html
✅  styling/draw-order.html
✅  styling/zoom-range-style.html
✅  styling/style-by-number.html
✅  styling/style-by-category.html
✅  styling/image-multiple.html
✅  styling/viewport.html
✅  styling/image-single.html
✅  styling/color-spaces.html
✅  styling/scaled.html
✅  styling/filter.html
✅  styling/zoom-range-filter.html
✅  sources/sql-source-layer.html
✅  sources/geojson-source-layer.html
✅  sources/multiple-layers.html
✅  sources/select-layer.html
✅  sources/external-geojson.html
✅  editor/index.html
✅  widgets/histogram-widget-viewport.html
✅  widgets/category-widget-viewport.html
✅  widgets/numeric-chart.html
✅  widgets/viewport-summary.html
✅  widgets/category-chart.html
✅  widgets/weighted-histogram-table.html

### CODE REVIEW

**Comment by elenatorro** [comment]
Notes:

- I've removed the `step-n.html` files that we're not being used and rearranged the steps to be consistent where needed.
- I've tested reference, examples and guides with the new arrangement they're working fine.
- I've also tested debug examples. I've organized a bit the examples in the `debug` directory and all of them are working fine.
- I left advanced 'landing-page'  examples, we can discuss later were we want to place them and/or if we want to make any of them public.

cc @makella

**Comment by makella** [comment]
@elenatorro thank you so much! I'm taking a look through now, and I'll go through the list I put together in the original ticket based off of Raul's.

**Comment by makella** [comment]
@elenatorro 
First set of changes: advanced examples (more coming soon just want to break them up by section)

- [x] deleted landing page examples as that was taken care of with this issue: https://github.com/CartoDB/website/issues/4358#issuecomment-472405306

- [x] modified symbology for hurricane harvey example as described in this issue: 
https://github.com/CartoDB/carto-vl/issues/1250#issuecomment-466946783

more coming...

**Comment by makella** [comment]
@elenatorro great working on this together!

I looked through the debug folders and there aren't any examples that I think we need to add right now... 

A summary of our reorganization of the examples section work:

- [x] Added a Sources section
  - moved source related examples from basics to this section
  - added a geojson source layer example
  - moved load geojson source layer from advanced section to sources section
- [x] Widgets section
  - replaced numeric and category chart examples with latest from the Build Custom Charts guide to show the workflow with viewportHistogram
- [x] Interactivity
  - separated adding pop-ups into two examples: one for click and one for hover instead of one for both

In addition:
- [x] Animation
  - fixed inconsistencies with coloring/opening zoom between the examples
- [x] Styling section
  - added zoom range style example
  - added zoom range filter example
  - added more category buckets and enhanced symbology for style-by-category example
  - reduced the symbol size for viewport.html (it was too large and symbology wasn't clear)
  - added full words (vs. Asc / Desc) for draw-order.html
  - went through and removed some unneeded comments (define layer, define user, etc.) and spaces through the examples in this section
- [x] Advanced
  - modified the basemap and line styling of the classification variables example

Comments/Questions:
- Staging branch is updated with all of these changes
  - I went through each example and everything seems to be working fine
- I didn't have a chance to do a thorough look through all the guides to see if they might be referencing any examples with changed URLs. I don't think that we have any of these and from the skim that I did, didn't see anything, but would be good if you could take a quick look at this too.

**Comment by elenatorro** [comment]
Really nice, @makella, this work is extraordinary ✨ . I just did the check in the guides and everything seems fine. I think we're ready to merge this 🎉

**Comment by makella** [comment]
BOOM

**Pull request merged**
