### PR TITLE
Update event

### PR DESCRIPTION
**Pull request by davidmanzanares**
Adds a new `update` event which is fired every time that the map is moved, the viz changes (including animation) or new data is loaded. This is very practical for reacting to render external widgets.

cc: @rubenmoya

### CODE REVIEW

**Comment by Jesus89** [comment]
+Tests please ;)

**Comment by davidmanzanares** [comment]
How do you imagine testing this? I mean, you would need to know when dataframes are added, when map is moved... I don't want to create a lot of fake internals and test the implementation

**Comment by Jesus89** [comment]
I'm not very happy using a generic event for lots of things, so we should revisit this in the future. But since its part of the API it should have tests to cover all its functionality.

To tackle this we must implement "user tests" to work with a real map (div). Let me help you with that ;)

**Comment by Jesus89** [comment]
UPDATE: added user tests and a bit of refactoring/renaming.

LGTM, but @davidmanzanares take a look please :wink:

**Comment by davidmanzanares** [comment]
:+1: Thanks!

**Pull request merged**
