### PR TITLE
Using our mgl fork

### PR DESCRIPTION
**Pull request by Jesus89**
Related to https://github.com/CartoDB/carto-vl/issues/333

## MGL fork repo ([Link](https://github.com/CartoDB/mapbox-gl-js))
We use this fork to enable the custom layer capabilities in the MGL library. Main branches are:
- `carto`: this is our default branch. It comes from `v0.44.1` tag and contains the `webgl-layer` branch merged. This is the main branch for us. NPM packages are published from here using prereleases to keep the original version: [npm package](https://www.npmjs.com/package/@carto/mapbox-gl). The current version is `v0.44.1-carto1`.
- `webgl-layer`: this is the branch containing our PR for the "custom layers" support.
- `master`: this is the master branch. It should be up to date with the upstream.

## CARTO VL repo
I have removed the bundle from the `vendor` directory so now we use the bundle directly from npm:
- `tests`: `@carto/mapbox-gl` has been added to our **devDependencies** to be used in the integration and acceptance tests.
- `examples`: the examples now use the same version of the npm package directly from unpkg.

### CODE REVIEW

**Comment by Jesus89** [comment]
Well, it seems that v0.44.1 is working OK (tests, examples)

Also, the merge with v0.44.1 didn't generate any conflict.

**Comment by davidmanzanares** [comment]
But... weren't we already ahead of 0.44.1?

**Comment by Jesus89** [comment]
Yes.

I started the `carto` branch in the v0.44.1 tag, but then I merged `webgl-layer` branch into the carto branch, and added the `webgl-layer2` fix. So the code should be the same that we were using.

**Comment by Jesus89** [comment]
Now, the master branch points to the v0.45.0-beta1 version, so we could update the `carto` branch from `master` and test it in other PR.

**Comment by Jesus89** [comment]
We have decided to wait until the MGL v0.45.0 stable version to do the acceptance and merge of this PR,

**Pull request merged**
