### PR TITLE
Compute metadata based on viz to reduce properties

### LINKED ISSUE #317: GeoJSON improvements
- [x] Performance when having several categories
  - [x] Property lookup is slow due to linear search.
  - [x] Only use required columns based on `viz.getMinimumNeededSchema` as in Windshaft.
- [x] Smell: `requestMetadata` doesn't use `viz`.
- [x] JSON.parse/JSON.stringify for cloning the orignal data.
- [x] If present, it should use cartodb_id from original data. Use case: using SQL API to retrieve GeoJSON.

### PR DESCRIPTION
**Pull request by rochoa**
The DataFrame is computed on demand, without having to precompute features
from the original data. This removes the clone of the data. It also allows using the
cartodb_id from original data.

This fixes #317.

### CODE REVIEW

**Comment by rochoa** [comment]
@Jesus89, using negative cartodb_id was on purpose. How was that affecting the tests?

**Comment by Jesus89** [comment]
OK. If this is a feature we should update the interactivity tests. Let me do it

**Comment by rochoa** [comment]
I updated this PR with @davidmanzanares' one.

**Comment by Jesus89** [comment]
:+1:

**Pull request merged**
