### PR TITLE
Mapbox gl integration

### PR DESCRIPTION
**Pull request by IagoLast**
https://github.com/CartoDB/renderer-prototype/issues/44
---

This PR uses our own fork from a CDN in the examples while `carto-vl` support is not included in the mapboxgl repo.

cc @rochoa @Jesus89 @davidmanzanares

### CODE REVIEW

**Comment by Jesus89** [comment]
As we talked off-line, we should upload those packages to our CDN (S3 bucket) and use it from there.

I would also remove our fork of mapboxgl from `npm`.

**Comment by IagoLast** [comment]
> I would also remove our fork of mapboxgl from npm

why?

**Comment by Jesus89** [comment]
We will use our CDN instead of unpkg.

**Comment by IagoLast** [comment]
> We will use our CDN instead of unpkg.

ok but in any case this is not important now

**Pull request merged**
