### PR TITLE
Use a generic cache

### PR DESCRIPTION
**Pull request by IagoLast**
Following https://github.com/CartoDB/carto-vl/pull/487/files#r196074418

### CODE REVIEW

**Comment by davidmanzanares** [comment]
I already answered to your request in the original PR

**Comment by IagoLast** [comment]
@davidmanzanares yep, and I think you didn't understand my comment that's why created this PR so you can see the approach

**Comment by davidmanzanares** [comment]
I did understand your comment

**Comment by jgoizueta** [comment]
My unrequested opinion: I'm now quite sure which approach I like best, and I see no problem with the original, so I'd keep it as is. But what do I know? (specially about JS) ¯\_(ツ)_/¯

**Comment by IagoLast** [comment]
ok guys, I surrender ¯\_(ツ)_/¯

**Pull request closed without merging**
