### PR TITLE
Offset symbol

### PR DESCRIPTION
**Pull request by davidmanzanares**
Fix for https://github.com/CartoDB/carto-vl/issues/819

### CODE REVIEW

**Comment by elenatorro** [comment]
It works great ✨ I know we are adding offset examples here https://github.com/CartoDB/carto-vl/issues/822, but I think it would be great to add an example in `placement.js` showing the difference between `symbolPlacement` and `offset`, or at least that you can combine both. What do you think?

**Comment by davidmanzanares** [comment]
Ok, but I wouldn't publish it since I think that the example should be with an explanation in one guide (and the guide is out of the scope for this).

**Comment by elenatorro** [comment]
I agree it is out of the scope, but I mean to add an example using placement with offset, so the user can see it does not need to be used only with symbolPlacement.

**Comment by elenatorro** [comment]
I did not mean an html example, but a code example in `placement.js` with JS API / String API.

**Comment by davidmanzanares** [comment]
To be honest, I wouldn't add an example with `offset` in the placement reference. I think they don't have special meaning when combined, they just (now) play well with each other, or better said, they don't interfere with each other.

**Comment by elenatorro** [comment]
Ok, not combined but at least an example using only placement with offset, because we do not have any code example showing this, and it seems that placement is only available for `symbolPlacement` while it can be used with `offset`. I think it is a useful and simple example, but this is just a personal opinion, so if you think it is not necessary, then it is ok. The rest LGTM.

**Comment by davidmanzanares** [comment]
Oh, ok, now I understand you. I was confusing "placement" with "symbolPlacement". Yes, we totally miss an example with `offset` (which needs a "placement").

In fact, there exist an issue that deprecates placement for offset (https://github.com/CartoDB/carto-vl/issues/361) and introduces "translate" and "rotate".

I think we should tackle that one.

**Comment by elenatorro** [comment]
LGTM since we do not need to add documentation to offset because we are going to add an equivalent `transform` property and `translate` expression.

**Pull request merged**
