### PR TITLE
Re-use exquisite's browser instance to speed-up tests

### PR DESCRIPTION
**Pull request by rochoa**
This depends on IagoLast/Exquisite#11

### CODE REVIEW

**Comment by IagoLast** [comment]
> This depends on IagoLast/Exquisite#11

Just released v1.4.0 🎉

**Comment by rochoa** [comment]
Thanks for helping with this. 💪 

This branch is based on my other branch reporting errors in tests, that's why we are getting the `Another atomic change was done before this one committed` error.

**Comment by IagoLast** [comment]
This fu**ing atomic change It's driving me crazy!

I think is related to https://github.com/CartoDB/carto-vl/issues/321

**Comment by Jesus89** [comment]
Fount that headless mode is not working anymore on linux :(

**Comment by IagoLast** [comment]
im going to be "that guy again" but do we have measures about the actual speed improvement of this?

**Comment by Jesus89** [comment]
~60% less time

**Comment by rochoa** [comment]
I'm merging this into `handle-errors-during-exquisite-tests`, so we can decide to merge all that into master.

**Pull request merged**
